Presentation Layer/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using UserPortalValdiationsDBContext.Filters;
using UserPortalValdiationsDBContext.Models;
using UserPortalValdiationsDBContext.Services.Interfaces;
using UserPortalValdiationsDBContext.ViewModels;
using UserPortalValdiationsDBContext.Services.Interfaces;
namespace UserPortalValdiationsDBContext.Controllers
{
    [ServiceFilter(typeof(LoggingActionFilter))]
    [ServiceFilter(typeof(AuditingFilter))]
    [ServiceFilter(typeof(ErrorHandlingFilter))]
    public class DashboardController : Controller
    {
        private readonly IUserService UserService;
        private readonly IAddressService AddressService;

        public DashboardController(IUserService userService, IAddressService addressService)
        {
            UserService = userService;
            AddressService = addressService;
        }

        [ServiceFilter(typeof(ResultCacheFilter))]  // Cache Dashboard index page for performance
        public IActionResult Index()
        {
            var users = UserService.GetAllUsers();

            if (HttpContext.User.Identity!.IsAuthenticated)
            {
                var name = HttpContext.User.Identity.Name;
                var loggedUser = UserService.GetUserByUsername(name!);

                if (loggedUser != null)
                {
                    loggedUser.LastLoginAt = DateTime.Now;
                    UserService.UpdateUser(loggedUser);
                }
            }

            return View(users);
        }

        [ServiceFilter(typeof(ActionValidationFilter))]
        public IActionResult Edit(int id)
        {
            var user = UserService.GetUserById(id);
            if (user == null) return NotFound();

            return View(user);
        }

        [HttpPost]
        [ServiceFilter(typeof(ActionValidationFilter))]
        public IActionResult Edit(User user)
        {
            user.LastPasswordChangeAt = DateTime.Now;
            UserService.UpdateUser(user);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            UserService.DeleteUser(id);
            return RedirectToAction("Index");
        }

        public IActionResult AddAddress(int userId) => View(new AddressViewModel { UserId = userId });

        [HttpPost]
        [ServiceFilter(typeof(ActionValidationFilter))]
        public IActionResult AddAddress(AddressViewModel model)
        {
            AddressService.AddAddress(model);
            TempData["msg"] = "Address added successfully!";
            return RedirectToAction("UserAddresses", new { userId = model.UserId });
        }

        public IActionResult EditAddress(int id)
        {
            var vm = AddressService.GetAddressVMById(id);
            if (vm == null) return NotFound();
            return View(vm);
        }

        [HttpPost]
        [ServiceFilter(typeof(ActionValidationFilter))]
        public IActionResult EditAddress(AddressViewModel model)
        {
            AddressService.UpdateAddress(model);
            return RedirectToAction("UserAddresses", new { userId = model.UserId });
        }

        public IActionResult DeleteAddress(int id)
        {
            AddressService.DeleteAddress(id);
            return RedirectToAction("Index");
        }

        public IActionResult UserAddresses(int userId)
        {
            var user = UserService.GetUserById(userId);
            if (user == null) return NotFound();

            var addresses = AddressService.GetAddressesByUserId(userId);

            var vm = new UserAddressListViewModel
            {
                UserId = userId,
                Username = user.Username,
                Addresses = addresses
            };

            return View(vm);
        }
        // this logic handles with years also 
        public IActionResult Birthdays()
        {
            var today = DateTime.Today;

            var upcoming = UserService.GetAllUsers()
                .Where(u => u.DateOfBirth.HasValue)
                .Select(u => new
                {
                    User = u,
                    NextBirthday = new DateTime(
                        today.Year,
                        u.DateOfBirth!.Value.Month,
                        u.DateOfBirth.Value.Day
                    ) < today
                    ? new DateTime(
                        today.Year + 1,
                        u.DateOfBirth.Value.Month,
                        u.DateOfBirth.Value.Day
                    )
                    : new DateTime(
                        today.Year,
                        u.DateOfBirth.Value.Month,
                        u.DateOfBirth.Value.Day
                    )
                })
                .OrderBy(x => x.NextBirthday)
                .Select(x => x.User)
                .ToList();

            return View(upcoming);
        }


    }
}

























/*using Microsoft.AspNetCore.Mvc;
using UserPortalValdiationsDBContext.Interfaces;
using UserPortalValdiationsDBContext.Models;
using UserPortalValdiationsDBContext.ViewModels;

namespace UserPortalValdiationsDBContext.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IUserService UserService;
        private readonly IAddressService AddressService;

        public DashboardController(IUserService userService, IAddressService addressService)
        {
            UserService = userService;
            AddressService = addressService;
        }

        // ---------------------------
        // DASHBOARD HOME
        // ---------------------------
        public IActionResult Index()
        {
            var users = UserService.GetAllUsers();

            // Update "LastLoginAt" of current logged-in user (OPTIONAL)
            if (HttpContext.User.Identity!.IsAuthenticated)
            {
                var name = HttpContext.User.Identity.Name;
                var loggedUser = UserService.GetUserByUsername(name!);

                if (loggedUser != null)
                {
                    loggedUser.LastLoginAt = DateTime.Now;
                    UserService.UpdateUser(loggedUser);
                }
            }

            return View(users);
        }

        // ---------------------------
        // USER OPERATIONS
        // ---------------------------
        public IActionResult Edit(int id)
        {
            var user = UserService.GetUserById(id);
            if (user == null) return NotFound();

            return View(user);
        }

        [HttpPost]
        public IActionResult Edit(User user)
        {
            if (!ModelState.IsValid)
                return View(user);

            user.LastPasswordChangeAt = DateTime.Now; // Track password change
            UserService.UpdateUser(user);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            UserService.DeleteUser(id);
            return RedirectToAction("Index");
        }

        // ---------------------------
        // ADDRESSES
        // ---------------------------
        public IActionResult AddAddress(int userId)
        {
            return View(new AddressViewModel { UserId = userId });
        }

        [HttpPost]
        public IActionResult AddAddress(AddressViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            AddressService.AddAddress(model);

            TempData["msg"] = "Address added successfully!";
            return RedirectToAction("UserAddresses", new { userId = model.UserId });
        }

        public IActionResult EditAddress(int id)
        {
            var vm = AddressService.GetAddressVMById(id);
            if (vm == null) return NotFound();

            return View(vm);
        }

        [HttpPost]
        public IActionResult EditAddress(AddressViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            AddressService.UpdateAddress(model);

            return RedirectToAction("UserAddresses", new { userId = model.UserId });
        }

        public IActionResult DeleteAddress(int id)
        {
            AddressService.DeleteAddress(id);
            return RedirectToAction("Index");
        }

        public IActionResult UserAddresses(int userId)
        {
            var user = UserService.GetUserById(userId);
            if (user == null) return NotFound();

            var addresses = AddressService.GetAddressesByUserId(userId);

            var vm = new UserAddressListViewModel
            {
                UserId = userId,
                Username = user.Username,
                Addresses = addresses
            };

            return View(vm);
        }

        // ---------------------------
        // VIEW UPCOMING BIRTHDAYS PAGE
        // ---------------------------
        public IActionResult Birthdays()
        {
            var users = UserService.GetAllUsers();

            var upcoming = users
                .Where(u => u.DateOfBirth.Month >= DateTime.Today.Month)
                .OrderBy(u => u.DateOfBirth.Month)
                .ThenBy(u => u.DateOfBirth.Day)
                .ToList();

            return View(upcoming);
        }
    }
}















*/

Presentation Layer/ViewComponents/BirthdayCarouselViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using UserPortalValdiationsDBContext.Services.Interfaces;

namespace UserPortalValdiationsDBContext.ViewComponents
{
    public class BirthdayCarouselViewComponent : ViewComponent
    {
        private readonly IUserService _userService;

        public BirthdayCarouselViewComponent(IUserService userService)
        {
            _userService = userService;
        }

        public IViewComponentResult Invoke()
        {
            // var users = _userService.GetWeeklyBirthdays();
            var users = _userService.GetWeeklyBirthdays();

            return View(users);
        }
    }

}

Presentation Layer/ViewComponents/DepartmentChartViewComponent.cs
//Department BAR Chart + Dynamic Filtering
//1.Department Chart with Dynamic Filtering(when you click on graph it will filter the users from the database table..
using Microsoft.AspNetCore.Mvc;
using UserPortalValdiationsDBContext.Services.Interfaces;

namespace UserPortalValdiationsDBContext.ViewComponents
{
    public class DepartmentChartViewComponent : ViewComponent
    {
        private readonly IUserService _userService;

        public DepartmentChartViewComponent(IUserService userService)
        {
            _userService = userService;
        }

        public IViewComponentResult Invoke()
        {
            var data = _userService.GetUserCountByDepartmentChart();
            return View(data);
        }
    }

}


/*Department bar chart loads

Clicking a bar filters user table

All existing features continue working

No enum or casting issues
*/

Presentation Layer/ViewComponents/DepartmentCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using UserPortalValdiationsDBContext.Services.Interfaces;

namespace UserPortalValdiationsDBContext.ViewComponents
{
    public class DepartmentCountViewComponent : ViewComponent
    {
        private readonly IUserService _userService;

        public DepartmentCountViewComponent(IUserService userService)
        {
            _userService = userService;
        }

        public IViewComponentResult Invoke()
        {
            var data = _userService.GetUserCountByDepartment();
            return View(data);
        }
    }
}

Presentation Layer/ViewComponents/UserProfileSidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using UserPortalValdiationsDBContext.Services.Interfaces;

namespace UserPortalValdiationsDBContext.ViewComponents
{
    public class UserProfileSidebarViewComponent : ViewComponent
    {
        private readonly IUserService _userService;

        public UserProfileSidebarViewComponent(IUserService userService)
        {
            _userService = userService;
        }

        public IViewComponentResult Invoke(string? userId)
        {
            if (string.IsNullOrEmpty(userId))
                return Content("");

            var vm = _userService.GetUserProfileSidebar(userId);

            if (vm == null)
                return Content("");

            return View(vm);
        }
    }
}

Presentation Layer/Views/Dashboard/AddAddress.cshtml
@model UserPortalValdiationsDBContext.ViewModels.AddressViewModel

<h2>Add Address</h2>

<form asp-action="AddAddress" method="post">
    <input type="hidden" asp-for="UserId" />

    <div class="mb-3">
        <label asp-for="Line1" class="form-label">Address Line 1 *</label>
        <input asp-for="Line1" class="form-control" />
        <span asp-validation-for="Line1" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="City" class="form-label">City *</label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="State" class="form-label">State *</label>
        <input asp-for="State" class="form-control" />
        <span asp-validation-for="State" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Pin" class="form-label">PIN *</label>
        <input asp-for="Pin" class="form-control" />
        <span asp-validation-for="Pin" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Add</button>
    <a asp-action="UserAddresses" asp-route-userId="@Model.UserId" class="btn btn-secondary ms-2">Back</a>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Presentation Layer/Views/Dashboard/Edit.cshtml
@model UserPortalValdiationsDBContext.Models.User
@{
    ViewBag.Title = "Edit User";
}

<h2>Edit User</h2>

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="mb-3">
        <label asp-for="Username" class="form-label"></label>
        <input asp-for="Username" class="form-control" />
        <span asp-validation-for="Username" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Email" class="form-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Password" class="form-label"></label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Age" class="form-label"></label>
        <input asp-for="Age" class="form-control" type="number" min="0" />
        <span asp-validation-for="Age" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Phone" class="form-label"></label>
        <input asp-for="Phone" class="form-control" />
        <span asp-validation-for="Phone" class="text-danger"></span>
    </div>

    <div class="d-flex justify-content-between">
        <button type="submit" class="btn btn-primary">Save</button>
        <a asp-controller="Dashboard" asp-action="Index" class="btn btn-secondary">Back</a>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Presentation Layer/Views/Dashboard/EditAddress.cshtml
@model UserPortalValdiationsDBContext.ViewModels.AddressViewModel

<h2>Edit Address</h2>

<form asp-action="EditAddress" method="post">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="UserId" />

    <div class="mb-3">
        <label asp-for="Line1" class="form-label">Address Line 1 *</label>
        <input asp-for="Line1" class="form-control" />
        <span asp-validation-for="Line1" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="City" class="form-label">City *</label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="State" class="form-label">State *</label>
        <input asp-for="State" class="form-control" />
        <span asp-validation-for="State" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Pin" class="form-label">PIN *</label>
        <input asp-for="Pin" class="form-control" />
        <span asp-validation-for="Pin" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
    <a asp-action="UserAddresses" asp-route-userId="@Model.UserId" class="btn btn-secondary ms-2">Back</a>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Presentation Layer/Views/Dashboard/Index.cshtml
 @model IEnumerable<UserPortalValdiationsDBContext.Models.User>

@{
    ViewBag.Title = "Dashboard";
}

<h2 class="mb-4 fw-bold">📊 User Dashboard</h2>

<!-- 🔹 TOP WIDGETS -->
<div class="row g-4 mb-4">

    <div class="col-md-4">
        <div class="card shadow-sm h-100">
            <div class="card-body">
                @await Component.InvokeAsync("UserProfileSidebar")
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card shadow-sm h-100">
            <div class="card-body text-center">
                @await Component.InvokeAsync("DepartmentCount")
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card shadow-sm h-100">
            <div class="card-header bg-warning text-dark">
                🎂 Birthdays This Month
            </div>
            <div class="card-body">
                @await Component.InvokeAsync("BirthdayCarousel")
            </div>
        </div>
    </div>


</div>

<!-- 🔹 DEPARTMENT BAR CHART -->
<div class="card shadow-sm mb-4">
    <div class="card-header bg-primary text-white">
        <h5 class="mb-0">👥 Users by Department</h5>
        <small>Click a bar to filter users below</small>
    </div>
    <div class="card-body">
        @await Component.InvokeAsync("DepartmentChart")
    </div>
</div>

<!-- 🔹 ACTION BAR -->
<div class="mb-3 d-flex justify-content-between align-items-center">
    <a class="btn btn-success"
       asp-controller="Account"
       asp-action="Register">
        ➕ Add New User
    </a>

    <form asp-controller="Account"
          asp-action="Logout"
          method="post">
        <button type="submit" class="btn btn-danger">
            🔒 Logout
        </button>
    </form>
</div>

<!-- 🔹 USERS TABLE -->
<div class="card shadow-sm">
    <div class="card-header bg-dark text-white">
        <h5 class="mb-0">📋 User List</h5>
    </div>

    <div class="card-body p-0">
        <table class="table table-striped table-bordered align-middle mb-0">
            <thead class="table-dark">
                <tr>
                    <th>Id</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Age</th>
                    <th>Phone</th>
                    <th style="width: 280px;">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var u in Model)
                {
                    <tr data-department="@u.Department">
                        <td>@u.Id</td>
                        <td>@u.Username</td>
                        <td>@u.Email</td>
                        <td>@u.Age</td>
                        <td>@u.Phone</td>
                        <td>
                            <a class="btn btn-sm btn-primary"
                               asp-action="Edit"
                               asp-route-id="@u.Id">✏️ Edit</a>

                            <a class="btn btn-sm btn-info text-white"
                               asp-action="AddAddress"
                               asp-route-userId="@u.Id">🏠 Address</a>

                            <a class="btn btn-sm btn-secondary"
                               asp-action="UserAddresses"
                               asp-route-userId="@u.Id">📋 Addresses</a>

                            <a class="btn btn-sm btn-danger"
                               href="javascript:void(0)"
                               onclick="showDelete('@Url.Action("Delete", "Dashboard", new { id = u.Id })')">
                                🗑 Delete
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@await Html.PartialAsync("_DeletePopup")

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Presentation Layer/Views/Dashboard/UserAddresses.cshtml
@model UserPortalValdiationsDBContext.ViewModels.UserAddressListViewModel

<h2>@Model.Username's Addresses</h2>

<a asp-action="AddAddress" asp-route-userId="@Model.UserId" class="btn btn-success mb-3">➕ Add Address</a>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Line1</th>
            <th>City</th>
            <th>State</th>
            <th>PIN</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var a in Model.Addresses)
        {
            <tr>
                <td>@a.Line1</td>
                <td>@a.City</td>
                <td>@a.State</td>
                <td>@a.Pin</td>
                <td>
                    <a asp-action="EditAddress" asp-route-id="@a.Id" class="btn btn-sm btn-primary">✏️ Edit</a>
                    <a asp-action="DeleteAddress" asp-route-id="@a.Id" class="btn btn-sm btn-danger">🗑 Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>